#+TITLE: Open source projects by Heini Fagerlund (@hfagerlund)
#+DATE: \today
#+AUTHOR: Heini Fagerlund
#+EMAIL: 
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:nil arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+CREATOR: Emacs 24.5.1 (Org mode 8.2.10)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \setlength{\parskip}{20pt}
#+LATEX_HEADER_EXTRA: \usepackage{underscore}
#+LATEX_HEADER_EXTRA: \usepackage{breakurl}
#+LATEX_HEADER_EXTRA: \usepackage{url}
#+LATEX_HEADER_EXTRA: \PassOptionsToPackage{hyphens}{url}
#+LATEX_HEADER_EXTRA: \usepackage{hyperref}
#+STARTUP: showall
#+BIBLIOGRAPHY: opensource-bib plain

* Projects by @hfagerlund
- *machine-learning-classifier-iris*
  \paragraph{}
  A comparison of machine learning algorithms for making predictions written in Python (v3.7) and using a built-in dataset included with scikit-learn \cite{machinelearning}. Data visualizations are also included.
   \paragraph{}
  This repository contains new feature development continued from the Jupyter version \cite{jupyter}.
- *mkdocs-docskimmer*
  \paragraph{}
  docSkimmer is an accessible, responsive, minimalist theme originally built for the static documentation site-generator MkDocs. Visit the [[http://bitsof.bytesofdesign.com/mkdocs-docskimmer/][documentation site]].
  \paragraph{}
  The docSkimmer theme has also been ported for Jekyll.
- *jekyll-docskimmer-theme*
   \paragraph{}
  jekyll-docskimmer-theme is the official port of [[https://github.com/hfagerlund/mkdocs-docskimmer][docSkimmer theme]] to Jekyll.
- *strip_anchors*
   \paragraph{}
   Source code for the custom strip_anchors Twig extension. This repository shows how the filter can be used in a Symfony 4 project to transform HTML content into valid RSS content for a feed \cite{stripanchors}.
- *elections-carousel-component*
   \paragraph{}
   This project is a component-based carousel presentation of election results data from a JSON API. Built using React and Webpack \cite{elections-carousel-component}.
- *hfagerlund.github.io*
   \paragraph{}
   My GitHub Pages site which currently serves as a table of contents listing of my open-source projects on GitHub \cite{ghpages}.
- *git-add-msg*
   \paragraph{}
   git-add-msg is a git extension that can be used to automatically update Trac tickets with comments without leaving the command-line interface \cite{git-add-msg}.
- *blog*
   \paragraph{}
   This (mirror) repository includes modualar scripts for a page scroller and page event analytics tracking \cite{blog}.

#+BEGIN_LaTeX
\begin{sloppypar}
\bibliographystyle{plain}
\bibliography{opensource-bib}
\end{sloppypar}
#+END_LaTeX
